name: Build and Release

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        keyboard: [ergodox_ez, mint60]
    steps:
    - uses: actions/checkout@v2
    - name: Build with Docker
      run: |
        docker run -e KEYBOARD=${{ matrix.keyboard }} -e KEYMAP=custom -v $(pwd):/qmk_firmware:rw edasque/qmk_firmware
